import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Shopify GraphQL codegen output (gitignored, regenerated by
    // `pnpm graphql-codegen` — see .graphqlrc.ts). storefront.generated.d.ts
    // carries eslint-disable comments for a plugin this project doesn't
    // install, which ESLint otherwise reports as an error.
    'lib/shopify/storefront.types.d.ts',
    'lib/shopify/storefront.generated.d.ts',
  ]),
]);

export default eslintConfig;
